window.myMain = new Main();
new Blog();
new Photoalbum(myMain);
window.vkImport = new VKImport(myMain);
new Videoplaylist(myMain);
new EnsUtility(myMain);
new FacebookImport();
new StartNow();
new ImportButtons(myMain);
//window.youtubeImport = new YoutubeImport();
new ImportButtons(myMain);
